return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  dependencies = { { "echasnovski/mini.nvim", version = "*" } },
  config = function()
    local wk = require("which-key")
    wk.setup({
      show_help = false,
      plugins = { spelling = true }, -- enabling this will show WhichKey when pressing z= to select spelling suggestions
      triggers = {
        { "<auto>", mode = "nxso" },
      },
    })
    wk.add({
      {
        mode = { "n", "v" },
        { "<leader>b", group = "Buffers" },
        { "<leader>bu", "<CMD>sort u<CR>", desc = "Retain unique values" },
        { "<leader>bc", "<CMD>normal! V<CR>:!bc<CR>", desc = "Evaulate Maths" },
        { "<leader>c", group = "Code" },
        { "<leader>cc", "<CMD>lua require('config.autocmds').toggle_color_column()<CR>", desc = "Toggle Color Column" },
        { "<leader>ch", "<CMD>lua require('config.autocmds').toggle_crosshairs()<CR>", desc = "No Highlight" },
        { "<leader>cw", "<CMD>lua require('config.autocmds').toggle_text_wrap()<CR>", desc = "Toggle Text Wrap" },
        { "<leader>cX", group = "Swap Previous" },
        { "<leader>cXc", desc = "Class" },
        { "<leader>cXf", desc = "Function" },
        { "<leader>cXp", desc = "Parameter" },
        { "<leader>cx", group = "Swap Next" },
        { "<leader>cxc", desc = "Class" },
        { "<leader>cxf", desc = "Function" },
        { "<leader>cxp", desc = "Parameter" },
        { "<leader>d", group = "Debug" },
        { "<leader>e", group = "Database" },
        { "<leader>f", group = "File" },
        { "<leader>g", group = "Git" },
        { "<leader>gh", group = "Hunk" },
        { "<leader>h", group = "Harpoon" },
        { "<leader>j", group = "Editing" },
        { "<leader>ja", "<CMD>e ~/repositories/workbench/l1.md<CR>", desc = "list 1" },
        { "<leader>jd", "<CMD>e ~/repositories/workbench/l3.md<CR>", desc = "list 3" },
        { "<leader>jh", "<CMD>e ~/repositories/workbench/help.md<CR>", desc = "help notes" },
        { "<leader>js", "<CMD>e ~/repositories/workbench/l2.md<CR>", desc = "list 2" },
        { "<leader>l", group = "LSP" },
        { "<leader>q", group = "Quit" },
        { "<leader>qq", "<CMD>lua require('utils').quit()<CR>", desc = "Quit" },
        { "<leader>qt", "<cmd>tabclose<cr>", desc = "Close Tab" },
        { "<leader>s", group = "Search" },
        { "<leader>sF", "<CMD>lua require('utils.telescope').grep_nvim_configs()<CR>", desc = "Grep Nvim Configs" },
        { "<leader>sN", "<CMD>lua require('utils.telescope').grep_notes()<CR>", desc = "Grep Notes" },
        { "<leader>sn", "<CMD>lua require('utils.telescope').search_notefiles()<CR>", desc = "Find Notes" },
        { "<leader>t", group = "Test/Table" },
        { "<leader>ts", "<CMD>execute 'normal! i' . strftime('%Y-%m-%d %H:%M:%S')<CR>", desc = "Insert Timestamps" },
        { "<leader>td", group = "Table Delete" },
        { "<leader>ti", group = "Table Insert" },
        { "<leader>v", group = "Virtual" },
        { "<leader>w", "<cmd>update!<CR>", desc = "Save" },
        { "<leader>z", group = "ZK" },
      },
    })
  end,
}
